language: csharp
solution: ci-experiments-dotnetcore.solution

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.0.1

script:
  - dotnet restore
  - dotnet build
  - cd UnitTestProject1 && dotnet test && cd ../
