language: csharp
solution: ci-experiments-dotnetcore.solution

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.1
    - os: osx
      osx_image: xcode7.2
      mono: none
      dotnet: 2.1

script:
  - dotnet restore
  - dotnet build
  - dotnet test UnitTestProject1
